announce = false
debug = true
description = 'test'
gamemode = 'Freeroam'
host = '0.0.0.0'
language = 'en'
modules = [ 'js-module' ]
name = 'Devserver - katsutosh'
players = 1024
port = 7788
resources = [ 'core', 'ct', 'ev_andy' ]
tags = [ 'customTag1', 'customTag2', 'customTag3', 'customTag4' ]
website = 'test.com'